// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'editor': string;
  'main': string;
  'top': string;
}
declare var cssExports: CssExports;
export = cssExports;
